apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  testAction:
    steps:
      - id: testAction
        name: Test publish-evidence-item action
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: >
            ## Test markup and property rendering

            - Run ID: ${{ cloudbees.run_id }}

            - Color test: <span style="color:green">This text should be green</span>

            - [backend.tar](https://ourcompany.com/repo/backend.tar)
