apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      param1:
        type: string
      param2:
        type: number
      param3:
        type: choice
        options:
          - "1"
          - "2"
      s4:
        type: string
      s5:
        type: string
      s6:
        type: string
      s7:
        type: string
      s8:
        type: string
      s10:
        type: string
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          sleep 30
          echo "hello world "
